// src/app/layout.tsx
import React from "react";
import { Footer, Navigation } from "@/components";
import "@/styles/globals.css";
import ReactQueryProvider from "@/providers/react-query";
export const metadata = {
  title: "Bishnu Dahal - Non-Profit Organization  ",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <ReactQueryProvider>
        <Navigation />
        <main>{children}</main>
        <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}


